//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPMVCIndraLaxmiImporium.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class BillCustomer
    {
        public int BillCustomerID { get; set; }
        [DisplayName("Debtor Name")]
        public Nullable<int> CustomerCode { get; set; }
        [DisplayName("Bill Number")]
        public Nullable<int> BillNumber { get; set; }
        public string CBM { get; set; }
        [DisplayName("Transport Name")]
        public string TransportCode { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        [DisplayName("Total Amount")]
        public string Total { get; set; }
    }
}
