//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPMVCIndraLaxmiImporium.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Ledger
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ledger()
        {
            this.LedgerTransactions = new HashSet<LedgerTransaction>();
        }
    
        public int LedgerID { get; set; }
        [DisplayName("Ledger Number")]
        [Required(ErrorMessage = "This field is required.")]
        public int LedgerNumber { get; set; }
        public string Type { get; set; }
        [DisplayName("Customer")]
        [Required(ErrorMessage = "This field is required.")]
        public Nullable<int> CustomerID { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LedgerTransaction> LedgerTransactions { get; set; }
    }
}
