//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPMVCIndraLaxmiImporium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewCustomerLedger
    {
        public int CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string Type { get; set; }
        public string PreviousBalance { get; set; }
        public string Mark { get; set; }
        public Nullable<int> LedgerNumber { get; set; }
    }
}
